# Generated by Django 4.2.2 on 2023-07-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acne.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('idContenido', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID contenido')),
                ('nombreContenido', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Prod')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acne.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
