# Generated by Django 4.2.2 on 2023-07-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acne', '0002_remove_contenido_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='nombreContenido',
            new_name='nombre',
        ),
    ]
