# Generated by Django 4.2.2 on 2023-07-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acne', '0003_rename_nombrecontenido_contenido_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='nombre',
            new_name='nombreContenido',
        ),
    ]
